import { Button } from "std-widgets.slint";

export component MainWindow {
    width: 1500px;
    height: 1000px;
    callback button_clicked();
    in-out property <bool> show_button: true;

    in-out property <length> square-x: 1500px;
    in-out property <length> square-y: 1000px;

    Rectangle {
        x: square-x;
        y: square-y;
        width: 50px;
        height: 50px;
        background: green;

        animate x { duration: 1000ms; easing: ease-in-out; }
        animate y { duration: 1000ms; easing: ease-in-out; }
    }

    if (root.show_button) : Button {
        text: "Start Game";
        clicked => { 
            root.button_clicked(); 
        }
    }
}